#version: "3.8"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    container_name: bff-keycloak
    command: start-dev --import-realm
    ports: ["8080:8080"]
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: test01


  bff:
    container_name: bff-bff
    build: ./bff
    ports:
      - "8081:8081"
      - "5005:5005"  # 🔥 Port de debug
    environment:
      - SPRING_OIDC_ISSUER=http://bff-keycloak:8080/realms/myrealm
      - SPRING_OIDC_CLIENT_ID=bff-client
      - SPRING_OIDC_CLIENT_SECRET=bff-secret
    #depends_on: [keycloak, apis]
    depends_on: [keycloak]
    volumes:
      - ~/.m2:/home/maven/.m2  # si l’utilisateur du conteneur est `maven`
      - ./bff:/app


  # apis:
  #   container_name: bff-apis
  #   build: ./apis
  #   ports: ["8084:8084"]
  #   environment:
  #     - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWK-SET-URI=http://keycloak:8080/realms/myrealm/protocol/openid-connect/certs
  #   volumes:
  #     - ~/.m2:/root/.m2  # monte le cache Maven du host dans le conteneur
      
  angular:
    container_name: bff-angular
    build: 
        context: ./frontend
        dockerfile: Dockerfile-prod
        #dockerfile: Dockerfile
    ports: ["4200:4200"]
    depends_on: [bff]
    volumes:
      - ./frontend:/app
      - /app/node_modules   # évite les conflits node_modules host <-> container
    environment:
      - CHOKIDAR_USEPOLLING=true  # pour que le watcher fonctionne dans Docker


  nginx:
    container_name: bff-nginx
    build: ./nginx
    ports:
      - 3001:80