server:
  port: 8081
  forward-headers-strategy: framework ## Cela dit à Spring de se baser sur les en-têtes X-Forwarded-* pour construire les URLs de redirection 

spring:
  security:
    oauth2:
      client:
        registration:
          bff-client:
            provider: keycloak
            client-id: ${SPRING_OIDC_CLIENT_ID}
            client-secret: ${SPRING_OIDC_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            #scope: openid,profile,api.read
            scope: openid,profile
        provider:
          keycloak:
            issuer-uri: ${SPRING_OIDC_ISSUER}

#  main:
#    web-application-type: reactive

  # session:
  #   cookie:
  #     http-only: true
  #     same-site: lax


  devtools:
    restart:
      enabled: true
      exclude: static/**,public/**


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure.security.oauth2: DEBUG
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.security.oauth2.client.registration: DEBUG